# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"hello_world": "00_core1.ipynb",
         "hello_world2": "00_core1.ipynb",
         "add": "01_core2.ipynb"}

modules = ["core1.py",
           "core2.py"]

doc_url = "https://akrishnamo.github.io/nbdev_test1/"

git_url = "https://github.com/akrishnamo/nbdev_test1/tree/master/"

def custom_doc_links(name): return None
