# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core1.ipynb (unless otherwise specified).

__all__ = ['hello_world', 'hello_world2']

# Cell
def hello_world():
    print('hello world')

# Cell
def hello_world2():
    '''prints the `hello world`  function twice'''
    hello_world()
    hello_world()

# Cell
hello_world2()